POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoibWF4aSIsImlkIjoiNjRlMmU5YjFjYzRiOWZmNTVkOWQwMzQ0IiwiaWF0IjoxNjkyODIyNTYxfQ.MsqXPag4MiC0M-WU1avIRxIC27IS14vv1T6b0rKaipE

{"title": "Advanced Next.JS", "author": "HyperMoon", "url": "http://hypermoon.com", "likes": 2}