POST http://localhost:3001/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoic251Z3MiLCJpZCI6IjY0NjgwNjk2ODE5MDM2NGMzY2Y1MDE2MyIsImlhdCI6MTY4NDY1NjU2MX0.77oiR-XYWE5HqHuLx2908e-yrs2TX_u7c2j8RTPeZzw

{"title": "frontend development", "author": "Fireship", "url": "http://fireship.com", "likes": 12}